import React from "react";
import {
  Activity,
  Apple,
  Award,
  Bed,
  Bike,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Building,
  Calculator,
  Calendar,
  Camera,
  Car,
  CheckCircle2,
  ChefHat,
  Clock,
  Cloud,
  Code2,
  Coffee,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  DollarSign,
  Droplets,
  Dumbbell,
  Eye,
  Feather,
  FileText,
  Film,
  Flame,
  FlaskConical,
  Folder,
  FolderGit2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  Hourglass,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Package,
  Palette,
  PartyPopper,
  Pencil,
  PenLine,
  Phone,
  PiggyBank,
  Plane,
  Play,
  Printer,
  Puzzle,
  Receipt,
  Rocket,
  Scale,
  Search,
  Server,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Speaker,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Sword,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Shared icon vocabulary for habits, projects, topics, and goals —
    replaces free-text emoji so entities render with real icons that
    match the app's lucide-based icon system instead of emoji glyphs. */
export const ICON_MAP = {
  activity: Activity,
  apple: Apple,
  award: Award,
  bed: Bed,
  bike: Bike,
  "book-open": BookOpen,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  building: Building,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  "check-circle": CheckCircle2,
  "chef-hat": ChefHat,
  clock: Clock,
  cloud: Cloud,
  code: Code2,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  "dollar-sign": DollarSign,
  droplets: Droplets,
  water: Droplets,
  dumbbell: Dumbbell,
  eye: Eye,
  feather: Feather,
  "file-text": FileText,
  film: Film,
  flame: Flame,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-git": FolderGit2,
  footprints: Footprints,
  gamepad: Gamepad2,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  hourglass: Hourglass,
  languages: Languages,
  laptop: Laptop,
  layers: Layers,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "party-popper": PartyPopper,
  pencil: Pencil,
  "pen-line": PenLine,
  phone: Phone,
  "piggy-bank": PiggyBank,
  plane: Plane,
  play: Play,
  printer: Printer,
  puzzle: Puzzle,
  receipt: Receipt,
  rocket: Rocket,
  scale: Scale,
  search: Search,
  server: Server,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  speaker: Speaker,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  sunrise: Sunrise,
  sword: Sword,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  trophy: Trophy,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  watch: Watch,
  waves: Waves,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICON_MAP;

export const DEFAULT_ICON: IconKey = "sparkles";

export const HABIT_ICONS: IconKey[] = [
  "sunrise",
  "sun",
  "moon",
  "bed",
  "book-open",
  "dumbbell",
  "activity",
  "heart-pulse",
  "footprints",
  "flame",
  "apple",
  "chef-hat",
  "utensils",
  "coffee",
  "droplets",
  "water",
  "waves",
  "bike",
  "brain",
  "smile",
  "pen-line",
  "pencil",
  "timer",
  "clock",
  "shield-check",
  "leaf",
  "heart",
  "target",
  "trophy",
  "award",
  "star",
  "sparkles",
  "check-circle",
  "calendar",
  "user",
  "users",
  "feather",
  "headphones",
  "music",
  "camera",
  "video",
  "gamepad",
  "code",
  "terminal",
  "laptop",
  "briefcase",
  "rocket",
  "lightbulb",
  "compass",
  "mountain",
  "globe",
  "wallet",
  "coins",
  "piggy-bank",
  "dollar-sign",
  "credit-card",
  "scale",
  "search",
  "lock",
  "eye",
  "zap",
];

export const PROJECT_ICONS: IconKey[] = [
  "rocket",
  "briefcase",
  "code",
  "terminal",
  "laptop",
  "cpu",
  "server",
  "folder",
  "folder-git",
  "package",
  "layers",
  "palette",
  "gem",
  "puzzle",
  "compass",
  "target",
  "lightbulb",
  "crown",
  "dollar-sign",
  "wallet",
  "coins",
  "piggy-bank",
  "building",
  "globe",
  "link",
  "lock",
  "shield-check",
  "gamepad",
  "film",
  "music",
  "mic",
  "video",
  "megaphone",
  "mail",
  "file-text",
  "hammer",
  "wrench",
  "trophy",
  "award",
  "star",
  "sparkles",
  "flame",
  "zap",
];

export const TOPIC_ICONS: IconKey[] = [
  "book-open",
  "graduation-cap",
  "brain",
  "lightbulb",
  "code",
  "terminal",
  "calculator",
  "flask-conical",
  "library",
  "languages",
  "globe",
  "newspaper",
  "file-text",
  "compass",
  "map-pin",
  "mountain",
  "palette",
  "music",
  "camera",
  "video",
  "mic",
  "headphones",
  "puzzle",
  "chess" in ICON_MAP ? ("chess" as IconKey) : "trophy",
  "star",
  "sparkles",
  "pencil",
  "pen-line",
  "eye",
  "search",
  "scale",
];

/** Best-effort map from legacy emoji strings to icon keys, used only by
    store migrations — never shown in the UI. */
export const EMOJI_TO_ICON: Record<string, IconKey> = {
  "🕌": "sunrise",
  "📖": "book-open",
  "📚": "book-open",
  "🏋️": "dumbbell",
  "🏋️‍♂️": "dumbbell",
  "📵": "shield-check",
  "🌙": "moon",
  "💧": "droplets",
  "🏃": "footprints",
  "🎯": "target",
  "🚀": "rocket",
  "📦": "package",
  "📅": "compass",
  "🧭": "compass",
  "🎨": "palette",
  "💻": "code",
  "🌐": "compass",
  "💼": "briefcase",
  "💎": "gem",
  "🎓": "graduation-cap",
  "🧮": "calculator",
  "🔬": "flask-conical",
  "📷": "camera",
  "🎵": "music",
  "🗣️": "languages",
  "🧠": "brain",
  "🔥": "flame",
  "✅": "shield-check",
  "🏠": "compass",
};

export function iconKeyFromLegacy(value: string | undefined): IconKey {
  if (!value) return DEFAULT_ICON;
  const trimmed = value.trim();
  if (trimmed in ICON_MAP) return trimmed as IconKey;
  if (EMOJI_TO_ICON[trimmed]) return EMOJI_TO_ICON[trimmed];

  const lower = trimmed.toLowerCase();
  if (lower in ICON_MAP) return lower as IconKey;

  const kebab = trimmed
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
  if (kebab in ICON_MAP) return kebab as IconKey;

  return DEFAULT_ICON;
}

export function getIconComponent(value: string | undefined): LucideIcon {
  const key = iconKeyFromLegacy(value);
  return ICON_MAP[key] ?? Sparkles;
}

export function DynamicIcon({
  name,
  className,
  style,
}: {
  name?: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const key = iconKeyFromLegacy(name);
  const IconComp = ICON_MAP[key] ?? Sparkles;
  return React.createElement(IconComp, { className, style });
}
